# Generated by Django 5.1 on 2024-08-25 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('intro_text', models.CharField(max_length=1000000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=5000)),
                ('camera', models.CharField(max_length=5000)),
                ('lens', models.CharField(max_length=5000)),
                ('date_shot', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('place', models.CharField(max_length=5000)),
                ('film', models.CharField(max_length=5000)),
                ('ISO', models.CharField(max_length=5000)),
                ('scan', models.CharField(max_length=5000)),
                ('notes', models.CharField(max_length=1000000)),
                ('tags', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
