# Generated by Django 5.1 on 2024-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_author_article_seperated_texts_article_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro_text',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='seperated_texts',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='notes',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
