# Generated by Django 5.1 on 2024-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_article_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(related_name='articles', to='posts.image'),
        ),
    ]
