# Generated by Django 5.1 on 2024-08-26 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='posts.story'),
        ),
    ]
