# Generated by Django 5.1 on 2024-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_category_tag_remove_article_story_remove_image_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='html_template',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='article',
            name='stories',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.story'),
        ),
    ]
