# Generated by Django 5.1 on 2024-08-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_name_category_title_rename_name_tag_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.article'),
        ),
        migrations.AddField(
            model_name='story',
            name='first_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.article'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
