# Generated by Django 5.1 on 2024-08-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_camera_film_lens_scanner_remove_image_iso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='lens',
        ),
    ]
