# Generated by Django 5.1 on 2024-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_image_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lens',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
