# Generated by Django 5.1 on 2024-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_image_lens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lens',
        ),
        migrations.DeleteModel(
            name='Lens',
        ),
    ]
