# Generated by Django 5.1 on 2024-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_camera_lens_remove_image_lens_delete_lens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='image',
            name='film',
        ),
        migrations.RemoveField(
            model_name='image',
            name='scanner',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
    ]
