# Generated by Django 5.1 on 2024-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_camera_film_lens_scanner_image_camera_image_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_template',
            field=models.CharField(blank=True, choices=[('article_template01.html', 'Story, links Text, rechts Bilder'), ('article_template02.html', 'Artikel, links Text, rechts Bilder')], max_length=5000),
        ),
    ]
