# Generated by Django 5.1 on 2024-08-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_article_author_alter_image_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticelLinker',
            new_name='ArticleLinker',
        ),
    ]
