# Generated by Django 5.1 on 2024-08-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_rename_articellinker_articlelinker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
    ]
