# Generated by Django 5.1 on 2024-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_cloud',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
