# Generated by Django 5.1 on 2024-08-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_image_image_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_cloud',
        ),
    ]
