# Generated by Django 5.1 on 2024-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_remove_article_tags_alter_article_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('images', models.ManyToManyField(to='posts.image')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.imagecluster'),
        ),
    ]
