# Generated by Django 5.1 on 2024-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecluster',
            name='images',
            field=models.ManyToManyField(related_name='imageclusters', to='posts.image'),
        ),
    ]
