# Generated by Django 5.1 on 2024-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_imagecluster_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecluster',
            name='title',
        ),
        migrations.AlterField(
            model_name='imagecluster',
            name='images',
            field=models.ManyToManyField(null=True, related_name='imageclusters', to='posts.image'),
        ),
    ]
