# Generated by Django 5.1 on 2024-08-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_rename_images_article_image_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_cluster',
            new_name='image_clusters',
        ),
    ]
