# Generated by Django 5.1 on 2024-08-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_rename_image_cluster_article_image_clusters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_clusters',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.image'),
        ),
        migrations.DeleteModel(
            name='ImageCluster',
        ),
    ]
