# Generated by Django 5.1 on 2024-08-31 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_articletext'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='accessories',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='build_material',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='custom_shutter_speed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='film_size',
            field=models.CharField(blank=True, choices=[('kleinbild', 'Kleinbild'), ('mittelbild', 'Mittelbild'), ('grossbild', 'Großbild')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='film_transport',
            field=models.CharField(blank=True, choices=[('manuell', 'manuell'), ('elektrisch', 'elektrisch')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='iso_setting',
            field=models.CharField(blank=True, choices=[('manuell', 'manuell'), ('automatisch', 'automatisch'), ('manuellundautomatisch', 'manuell und automatisch')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_production',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='lens_socket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('festverbaut', 'festverbaut'), ('austauschbar', 'austauschbar')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='lightmeter_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='max_iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='max_shutter_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='min_iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='min_shutter_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='modes',
            field=models.CharField(blank=True, choices=[('Vollautomatisch', 'Vollautomatisch'), ('Programm', 'Programm'), ('Blendenautomatik', 'Blendenautomatik'), ('Belichtungsautomatik', 'Belichtungsautomatik'), ('Manuell', 'Manuell')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='posts.camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='related_cameras',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cameras', to='posts.camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='similar_cameras',
            field=models.ManyToManyField(blank=True, null=True, related_name='similar_cameras', to='posts.camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='posts.camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='view_finder_type',
            field=models.CharField(blank=True, choices=[('SLR', 'SLR'), ('Messsucher', 'Messsucher'), ('elektrisch', 'elektrisch')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='focus_type',
            field=models.CharField(blank=True, choices=[('automatisch', 'automatisch'), ('Messsucher', 'Messsucher'), ('automatischundmanuell', 'automatisch und manuell'), ('manuell', 'manuell')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='min_focusdistance',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='first_production',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='modell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
