# Generated by Django 5.1 on 2024-08-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_camera_accessories_camera_build_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='modell',
            new_name='series',
        ),
    ]
