# Generated by Django 5.1 on 2024-08-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_rename_modell_camera_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='custom_shutter_speed',
            new_name='bulb',
        ),
        migrations.AddField(
            model_name='camera',
            name='battery',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
