# Generated by Django 5.1 on 2024-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_rename_custom_shutter_speed_camera_bulb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='color_variants',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='modes',
            field=models.CharField(blank=True, choices=[('Vollautomatisch', 'Vollautomatisch'), ('Programm', 'Programm'), ('Blendenautomatik', 'Blendenautomatik'), ('Belichtungsautomatik', 'Belichtungsautomatik'), ('Manuell', 'Manuell'), ('BelichtungsautomatikUndVollautomatisch', 'Belichtungsautomatik und vollautomatisch'), ('BlendenautomatikUndVollautomatisch', 'Blendenautomatik und vollautomatisch')], max_length=100, null=True),
        ),
    ]
