# Generated by Django 5.1 on 2024-09-01 14:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_alter_article_html_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro_text',
            field=tinymce.models.HTMLField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='film_size',
            field=models.CharField(blank=True, choices=[('Kleinbild', 'Kleinbild'), ('Mittelbild', 'Mittelbild'), ('Großbild', 'Großbild')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='modes',
            field=models.CharField(blank=True, choices=[('Vollautomatisch', 'Vollautomatisch'), ('Programm', 'Programm'), ('Blendenautomatik', 'Blendenautomatik'), ('Belichtungsautomatik', 'Belichtungsautomatik'), ('Manuell', 'Manuell'), ('Belichtungsautomatik und vollautomatisch', 'Belichtungsautomatik und vollautomatisch'), ('Blendenautomatik und Vollautomatisch', 'Blendenautomatik und vollautomatisch')], max_length=100, null=True),
        ),
    ]
