# Generated by Django 5.1 on 2024-09-02 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_alter_article_intro_text_alter_camera_film_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
