# Generated by Django 5.1 on 2024-09-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_delete_articletext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
    ]
