# Generated by Django 5.1 on 2024-09-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_remove_article_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.article')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
