# Generated by Django 5.1 on 2024-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(related_name='articles', through='posts.ArticleImage', to='posts.image'),
        ),
    ]
