# Generated by Django 5.1 on 2024-09-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_alter_articleimage_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
    ]
