# Generated by Django 5.1 on 2024-09-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_alter_articleimage_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_template',
            field=models.CharField(blank=True, choices=[('article_template01.html', 'Story, links Text, rechts Bilder'), ('article_template02.html', 'Artikel, links Text, rechts Bilder'), ('article_template03.html', 'Artikel, Text, Bild, Tabelle'), ('article_template04.html', 'Artikel, Objektiv')], max_length=5000),
        ),
    ]
