# Generated by Django 5.1 on 2024-09-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_alter_article_html_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default='False'),
        ),
    ]
