# Generated by Django 5.1 on 2024-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_article_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='public',
            field=models.BooleanField(default='False'),
        ),
    ]
